aarch64-linux-gnu-g++ -o tflite_profile_arm_xnnpack -Wl,--start-group \
build_tflite_2_11_1_ARM_XNNPACK/_deps/fft2d-build/libfft2d_alloc.a \
\
build_tflite_2_11_1_ARM_XNNPACK/_deps/fft2d-build/libfft2d_fftsg.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/fft2d-build/libfft2d_fftsg2d.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/fft2d-build/libfft2d_fftsg3d.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/fft2d-build/libfft2d_shrtdct.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/cpuinfo-build/deps/clog/libclog.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/cpuinfo-build/libcpuinfo.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/cpuinfo-build/libcpuinfo_internals.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/strings/libabsl_cord.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/strings/libabsl_cordz_sample_token.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/strings/libabsl_strings.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/strings/libabsl_cordz_handle.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/strings/libabsl_cordz_functions.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/strings/libabsl_cord_internal.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/strings/libabsl_strings_internal.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/strings/libabsl_str_format_internal.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/strings/libabsl_cordz_info.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/time/libabsl_time_zone.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/time/libabsl_time.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/time/libabsl_civil_time.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/types/libabsl_bad_any_cast_impl.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/types/libabsl_bad_optional_access.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/types/libabsl_bad_variant_access.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/profiling/libabsl_exponential_biased.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/profiling/libabsl_periodic_sampler.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/container/libabsl_hashtablez_sampler.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/container/libabsl_raw_hash_set.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/flags/libabsl_flags_config.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/flags/libabsl_flags_internal.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/flags/libabsl_flags_usage.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/flags/libabsl_flags_parse.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/flags/libabsl_flags_program_name.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/flags/libabsl_flags_usage_internal.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/flags/libabsl_flags_reflection.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/flags/libabsl_flags_marshalling.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/flags/libabsl_flags_commandlineflag_internal.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/flags/libabsl_flags_private_handle_accessor.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/flags/libabsl_flags_commandlineflag.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/flags/libabsl_flags.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/status/libabsl_status.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/status/libabsl_statusor.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/synchronization/libabsl_graphcycles_internal.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/synchronization/libabsl_synchronization.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/random/libabsl_random_internal_pool_urbg.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/random/libabsl_random_internal_randen_hwaes_impl.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/random/libabsl_random_internal_randen.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/random/libabsl_random_internal_distribution_test_util.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/random/libabsl_random_internal_platform.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/random/libabsl_random_distributions.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/random/libabsl_random_internal_seed_material.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/random/libabsl_random_seed_sequences.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/random/libabsl_random_internal_randen_hwaes.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/random/libabsl_random_internal_randen_slow.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/random/libabsl_random_seed_gen_exception.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/hash/libabsl_city.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/hash/libabsl_hash.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/hash/libabsl_low_level_hash.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/numeric/libabsl_int128.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/base/libabsl_base.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/base/libabsl_throw_delegate.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/base/libabsl_log_severity.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/base/libabsl_malloc_internal.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/base/libabsl_raw_logging_internal.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/base/libabsl_spinlock_wait.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/base/libabsl_scoped_set_env.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/base/libabsl_strerror.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/debugging/libabsl_symbolize.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/debugging/libabsl_stacktrace.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/debugging/libabsl_leak_check.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/debugging/libabsl_examine_stack.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/debugging/libabsl_failure_signal_handler.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/debugging/libabsl_demangle_internal.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/abseil-cpp-build/absl/debugging/libabsl_debugging_internal.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/flatbuffers-build/libflatbuffers.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/farmhash-build/libfarmhash.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_kernel_arm.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_denormal.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_wait.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_kernel_avx512.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_apply_multiplier.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_cpuinfo.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_pack_avx2_fma.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_tune.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_trmul.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_system_aligned_alloc.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_ctx.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_pack_avx512.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_context_get_ctx.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_blocking_counter.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_block_map.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_prepacked_cache.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_have_built_path_for_avx2_fma.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_have_built_path_for_avx.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_pack_arm.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_context.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_thread_pool.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_prepare_packed_matrices.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/profiler/libruy_profiler_profiler.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/profiler/libruy_profiler_instrumentation.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_kernel_avx2_fma.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_have_built_path_for_avx512.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_pack_avx.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_allocator.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_kernel_avx.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/ruy-build/ruy/libruy_frontend.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/gemmlowp-build/libgemmlowp_eight_bit_int_gemm.a \
build_tflite_2_11_1_ARM_XNNPACK/_deps/xnnpack-build/libXNNPACK.a \
build_tflite_2_11_1_ARM_XNNPACK/pthreadpool/libpthreadpool.a \
build_tflite_2_11_1_ARM_XNNPACK/tools/benchmark/libbenchmark_model.a \
build_tflite_2_11_1_ARM_XNNPACK/libtensorflow-lite.a \
-Wl,--end-group -lstdc++ -lpthread -lm -ldl -lrt -latomic -static  -g -O3 -DDEBUG -fPIC -mcpu=cortex-a55 -std=gnu++11 